# Dapr Pub/Sub Component Configuration
# This component connects Dapr to Strimzi-managed Kafka
#
# Reference: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-apache-kafka/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Kafka broker address (Strimzi bootstrap service)
    - name: brokers
      value: "todo-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"

    # Consumer group for this application
    - name: consumerGroup
      value: "todo-chatbot"

    # Authentication (none for local, sasl for production)
    - name: authType
      value: "none"

    # Disable TLS for local development
    - name: disableTls
      value: "true"

    # Initial offset for new consumer groups
    - name: initialOffset
      value: "oldest"

    # Maximum message size (1MB)
    - name: maxMessageBytes
      value: "1048576"

---
# Subscription for Backend Service (publishes events)
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: backend-subscription
  namespace: default
spec:
  topic: task-events
  routes:
    default: /events/task
  pubsubname: pubsub-kafka

---
# Subscription for Audit Service
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: audit-subscription
  namespace: default
spec:
  topic: task-events
  routes:
    default: /events/audit
  pubsubname: pubsub-kafka
  scopes:
    - audit-service

---
# Subscription for Reminder Service
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminder-subscription
  namespace: default
spec:
  topic: task-events
  routes:
    rules:
      - match: event.type == "task.created"
        path: /events/task-created
      - match: event.type == "task.updated"
        path: /events/task-updated
      - match: event.type == "task.deleted"
        path: /events/task-deleted
  pubsubname: pubsub-kafka
  scopes:
    - reminder-service

---
# Subscription for Recurring Service
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: recurring-subscription
  namespace: default
spec:
  topic: task-events
  routes:
    rules:
      - match: event.type == "task.completed"
        path: /events/task-completed
  pubsubname: pubsub-kafka
  scopes:
    - recurring-service
